"""dh seo — found on Google and in AI answers: detected, added per path, proved on rendered pages, and the owner's
part always in PENDING.md (stdlib unittest; the engine runs through node; HTTP is a fake)."""
import io
import json
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

SKILL = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SKILL))

from dhlib import deploy, guide, seo as SEO, state  # noqa: E402
from dhlib.cli import main  # noqa: E402
from dhlib.util import read_json, write_json  # noqa: E402

LAYOUT = '''import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: { canonical: "/" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
'''


def page(title="Artisan bakery in Lyon — Maison Pain", desc="Sourdough, viennoiseries and wedding cakes baked every morning in Lyon 2e. Order online, collect in store.",
         canonical="https://maisonpain.fr/", robots="index, follow", lang="en", h1=1, body="", extra_head=""):
    head = (f"<title>{title}</title>" if title is not None else "") + (f'<meta name="description" content="{desc}">' if desc else "")
    head += (f'<link rel="canonical" href="{canonical}">' if canonical else "") + f'<meta name="robots" content="{robots}">'
    head += '<meta name="viewport" content="width=device-width, initial-scale=1"><meta property="og:title" content="x"><meta property="og:image" content="https://maisonpain.fr/og.png"><meta name="twitter:card" content="summary_large_image">'
    return f'<html lang="{lang}"><head>{head}{extra_head}</head><body>{"<h1>Maison Pain</h1>" * h1}{body}</body></html>'


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        self.old = os.environ.get("DECKHAND_HOME")
        os.environ["DECKHAND_HOME"] = str(self.tmp / "home")
        self.root = self.tmp / "shop"
        self.root.mkdir()

    def tearDown(self):
        if self.old is None:
            os.environ.pop("DECKHAND_HOME", None)
        else:
            os.environ["DECKHAND_HOME"] = self.old
        shutil.rmtree(self.tmp, ignore_errors=True)

    def dh(self, *args):
        buf = io.StringIO()
        with redirect_stdout(buf):
            code = main(["--project", str(self.root), *args])
        return code, json.loads(buf.getvalue().strip().splitlines()[-1])

    def brief(self, **kw):
        b = {"name": "Maison Pain", "business": "Artisan bakery", "shape": "booking", "languages": ["en"], "audience": "Lyon locals",
             "brand": {"name": "Maison Pain", "tagline": "Sourdough baked every morning in Lyon", "primary": "#7c2d12"},
             "seo": {"keywords": ["artisan bakery lyon"], "locations": ["Lyon"], "local": {"category": "Bakery", "phone": "+33 4 72 00 00 00",
                                                                                           "address": "12 Rue Mercière, 69002 Lyon, FR"}}}
        for k, v in kw.items():
            cur = b
            parts = k.split("__")
            for p in parts[:-1]:
                cur = cur.setdefault(p, {})
            cur[parts[-1]] = v
        write_json(self.root / ".deckhand" / "brief.json", b)
        return b

    def next_app(self):
        (self.root / "package.json").write_text(json.dumps({"name": "shop", "dependencies": {"next": "16.3.6", "react": "19"}}), encoding="utf-8")
        (self.root / "tsconfig.json").write_text(json.dumps({"compilerOptions": {"paths": {"@/*": ["./*"]}}}), encoding="utf-8")
        (self.root / "app" / "about").mkdir(parents=True)
        (self.root / "app" / "layout.tsx").write_text(LAYOUT, encoding="utf-8")
        (self.root / "app" / "page.tsx").write_text("export default function Home() { return <main><h1>Maison Pain</h1></main>; }\n", encoding="utf-8")
        (self.root / "app" / "about" / "page.tsx").write_text('import type { Metadata } from "next";\n\nexport const metadata: Metadata = {\n  title: "Our bakers",\n};\n\nexport default function About() { return <h1>About</h1>; }\n', encoding="utf-8")
        write_json(self.root / ".deckhand" / "sitemap.json", {"pages": [{"route": "/", "title": "Home"}, {"route": "/about", "title": "About us"},
                                                                         {"route": "/account", "title": "Account", "auth": "user"}]})


class OwnerFacts(Base):
    def test_missing_facts_and_actions_go_to_pending_and_answered_ones_leave(self):
        state.init(self.root, "Maison Pain", path="scratch")
        self.brief()
        rep = SEO.audit(self.root, write=True)
        pending = (self.root / "PENDING.md").read_text(encoding="utf-8")
        self.assertIn("## Detected by `dh seo`", pending)
        self.assertIn("P-SEO-domain · ACTION NEEDED", pending)
        self.assertIn("P-SEO-seo.local.hours · ACTION NEEDED", pending)
        self.assertIn("P-SEO-gbp · ACTION NEEDED", pending)                       # local: Business Profile from day one
        self.assertNotIn("P-SEO-search_console", pending)                         # needs a domain first
        self.assertTrue(pending.index("## Detected") < pending.index("## Done"))
        self.assertIsNone(rep["score"])                                             # nothing to inspect yet: not measured, not "100"
        self.assertIn("SEO readiness not measured yet", pending)
        # the owner answers two facts; the first-asked date of the others survives the refresh
        lines = [(l[:-10] + "2026-01-02") if l.startswith("- [ ] P-SEO-seo.local.email ") else l for l in pending.splitlines()]
        (self.root / "PENDING.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.brief(domain="maisonpain.fr", seo__local__hours=["Mo-Sa 07:00-19:00"])
        SEO.audit(self.root, write=True)
        pending = (self.root / "PENDING.md").read_text(encoding="utf-8")
        self.assertNotIn("P-SEO-domain", pending)
        self.assertNotIn("P-SEO-seo.local.hours", pending)
        self.assertIn("P-SEO-search_console · ACTION NEEDED", pending)            # domain known → verify it in Search Console
        self.assertIn("P-SEO-bing · ACTION NEEDED", pending)
        self.assertIn("asked 2026-01-02", pending)
        self.assertEqual(pending.count("## Detected by `dh seo`"), 1)
        summary = guide.next_step(self.root)["pending"]
        self.assertGreater(summary["open"], 5)
        self.assertTrue(any(i["age_days"] and i["age_days"] > 200 for i in summary["items"]))

    def test_structured_data_holds_only_the_owners_facts(self):
        b = self.brief(brand__social=["https://instagram.com/maisonpain"], seo__local__hours=["Mo-Sa 07:00-19:00"])
        g = SEO.jsonld(b, "https://maisonpain.fr")["@graph"]
        biz, site = g
        self.assertEqual(biz["@type"], "Bakery")
        self.assertEqual(biz["address"], {"@type": "PostalAddress", "streetAddress": "12 Rue Mercière", "postalCode": "69002", "addressLocality": "Lyon", "addressCountry": "FR"})
        self.assertEqual(biz["sameAs"], ["https://instagram.com/maisonpain"])
        self.assertEqual(biz["openingHours"], ["Mo-Sa 07:00-19:00"])
        for invented in ("aggregateRating", "review", "email", "priceRange", "logo", "founder"):
            self.assertNotIn(invented, biz)
        self.assertEqual(site["@type"], "WebSite")
        self.assertEqual(SEO.schema_type({"shape": "saas", "brand": {}}), "Organization")


class RenderedPages(Base):
    ctx = None

    def setUp(self):
        super().setUp()
        self.brief(domain="maisonpain.fr", languages=["en"])
        self.ctx = SEO.ctx_of(self.root, "http://127.0.0.1:4100")

    def rules(self, route, html, headers=None, url="http://127.0.0.1:4100"):
        f, _ = SEO.check_page(route, 200, headers or {}, html, {**self.ctx, "url": url})
        return sorted({x["rule"] for x in f})

    def test_the_details_everyone_misses(self):
        self.assertEqual(self.rules("/", page()), [])
        self.assertIn("M01", self.rules("/", page(title="Create Next App")))
        self.assertIn("M03", self.rules("/", page(desc="Generated by create next app")))
        self.assertIn("M04", self.rules("/about", page(canonical="https://maisonpain.fr/")))          # inherited canonical
        self.assertIn("M04", self.rules("/about", page(canonical="/about")))                          # relative
        self.assertIn("C02", self.rules("/", page(robots="noindex")))                                 # on the local build: a bug
        self.assertIn("C02", self.rules("/", page(), headers={"x-robots-tag": "noindex"}))
        self.assertIn("T01", self.rules("/", page(h1=2)))
        self.assertIn("T03", self.rules("/", page(body='<img src="/a.jpg" width="1" height="1">')))
        self.assertIn("P02", self.rules("/", page(body='<img src="/a.jpg" alt="bread">')))
        self.assertIn("A06", self.rules("/", page(robots="index, max-snippet:0")))
        self.assertIn("M07", self.rules("/", page(lang="fr")))
        self.assertIn("T06", self.rules("/", page(body='<a href="/menu">click here</a>')))
        self.assertIn("M09", self.rules("/", page(extra_head='<meta name="keywords" content="bread">')))

    def test_previews_must_be_noindex_and_live_sites_must_use_the_real_domain(self):
        self.assertIn("C07", self.rules("/", page(), url="http://1.2.3.4.sslip.io"))
        self.assertNotIn("C02", self.rules("/", page(robots="noindex"), url="http://1.2.3.4.sslip.io"))
        live = {**self.ctx, "live": True, "url": "https://maisonpain.fr"}
        f, _ = SEO.check_page("/", 200, {}, page(canonical="http://localhost:3000/"), live)
        self.assertIn("M12", {x["rule"] for x in f})
        self.assertEqual(SEO.RULES["M12"]["severity"], "block")

    def test_multilingual_pages_need_reciprocal_hreflang(self):
        self.brief(domain="maisonpain.fr", languages=["en", "fr"])
        ctx = SEO.ctx_of(self.root, "http://127.0.0.1:4100")
        alts = '<link rel="alternate" hreflang="en" href="https://maisonpain.fr/en/"><link rel="alternate" hreflang="fr" href="https://maisonpain.fr/fr/">'
        f, _ = SEO.check_page("/", 200, {}, page(extra_head=alts), ctx)
        self.assertIn("I01", {x["rule"] for x in f})                                               # no x-default
        f, _ = SEO.check_page("/", 200, {}, page(extra_head=alts + '<link rel="alternate" hreflang="x-default" href="https://maisonpain.fr/en/">'), ctx)
        self.assertNotIn("I01", {x["rule"] for x in f})

    def test_structured_data_rules(self):
        good = [{"@type": "Bakery", "name": "M", "url": "u", "address": {"@type": "PostalAddress", "addressLocality": "Lyon"}, "telephone": "t", "logo": "l", "sameAs": ["s"], "openingHours": ["x"]},
                {"@type": "WebSite", "name": "M"}]
        self.assertEqual(SEO.check_graph(good, self.ctx), [])
        bad = [{"@type": "Bakery", "name": "M", "url": "u", "aggregateRating": {"ratingValue": 5}}, {"@type": "FAQPage"}]
        rules = {x["rule"] for x in SEO.check_graph(bad, self.ctx)}
        self.assertTrue({"S02", "S03", "S04", "S05", "S06", "S07", "L04"} <= rules, rules)

    def test_site_level_checks(self):
        pages = {"/": page(), "/about": page(canonical="https://maisonpain.fr/about")}
        write_json(self.root / ".deckhand" / "sitemap.json", {"pages": [{"route": "/"}, {"route": "/about"}, {"route": "/account", "auth": "user"}]})
        ctx = SEO.ctx_of(self.root, "http://127.0.0.1:4100")

        def get(robots, sitemap, soft404=False):
            def _get(url, follow=True, timeout=20):
                path = url.split("4100", 1)[1] if "4100" in url else "/"
                if path == "/robots.txt":
                    return 200, {}, robots
                if path == "/sitemap.xml":
                    return 200, {}, sitemap
                if path in pages:
                    return 200, {}, pages[path]
                return (200 if soft404 else 404), {}, ""
            return _get
        sm = "<urlset><url><loc>https://maisonpain.fr/</loc></url><url><loc>https://maisonpain.fr/account</loc></url></urlset>"
        f, _ = SEO.check_site("http://127.0.0.1:4100", ctx, get("User-agent: *\nDisallow: /\n", sm, soft404=True))
        rules = {x["rule"] for x in f}
        self.assertTrue({"C01", "C04", "C05", "C06"} <= rules, rules)
        c05 = next(x for x in f if x["rule"] == "C05")["detail"]
        self.assertIn("missing /about", c05)
        self.assertIn("lists signed-in pages /account", c05)
        f, _ = SEO.check_site("http://127.0.0.1:4100", ctx, get("User-agent: *\nAllow: /\n\nUser-agent: OAI-SearchBot\nDisallow: /\n\nSitemap: https://maisonpain.fr/sitemap.xml\n",
                                                                "<urlset><url><loc>https://maisonpain.fr/</loc></url><url><loc>https://maisonpain.fr/about</loc></url></urlset>"))
        self.assertEqual({x["rule"] for x in f}, {"A01"})

    def test_live_host_checks(self):
        ctx = {**SEO.ctx_of(self.root, "https://maisonpain.fr"), "live": True}

        def get(url, follow=True, timeout=20):
            if url == "http://maisonpain.fr/":
                return 200, {}, ""
            if url == "https://www.maisonpain.fr/":
                return 200, {}, ""
            if url.endswith("/robots.txt"):
                return 200, {}, "User-agent: *\nAllow: /\nSitemap: https://maisonpain.fr/sitemap.xml\n"
            if url.endswith("/sitemap.xml"):
                return 200, {}, "<urlset><url><loc>https://maisonpain.fr/</loc></url></urlset>"
            return 404, {}, ""
        f, _ = SEO.check_site("https://maisonpain.fr", ctx, get)
        details = [x["detail"] for x in f if x["rule"] == "C08"]
        self.assertEqual(len(details), 2, f)


class ApplyAndPaths(Base):
    @unittest.skipUnless(shutil.which("node"), "node not on PATH")
    def test_apply_adds_and_improves_never_overwrites_and_undoes_byte_exact(self):
        state.init(self.root, "Maison Pain", path="existing")
        self.brief(domain="maisonpain.fr")
        self.next_app()
        write_json(self.root / ".deckhand" / "copy.json", {"seo": {"pages": {"/": {"title": "Artisan bakery in Lyon — Maison Pain",
                                                                                   "description": "Sourdough and cakes baked every morning in Lyon 2e."}}}})
        before = {p: (self.root / p).read_bytes() for p in ("app/layout.tsx", "app/page.tsx", "app/about/page.tsx")}
        a = SEO.audit(self.root)
        code, out = self.dh("seo", "apply")
        self.assertEqual(code, 0, out)
        self.assertGreater(out["score"], a["score"])
        layout = (self.root / "app/layout.tsx").read_text(encoding="utf-8")
        self.assertIn("template: `%s — ${SITE.name}`", layout)
        self.assertNotIn('canonical: "/"', layout)                                  # the inherited canonical is gone
        self.assertIn('<html lang="en">', layout)
        self.assertIn("<JsonLd data={JSON_LD} />", layout)
        about = (self.root / "app/about/page.tsx").read_text(encoding="utf-8")
        self.assertIn('title: "Our bakers"', about)                                 # the owner's words stay
        self.assertIn('alternates: { canonical: "/about" }', about)
        robots = (self.root / "app/robots.ts").read_text(encoding="utf-8")
        self.assertIn('"/account"', robots)                                        # signed-in pages are not crawled
        site = (self.root / "lib/seo.ts").read_text(encoding="utf-8")
        self.assertIn('"https://maisonpain.fr"', site)
        self.assertIn('"Bakery"', site)
        key = read_json(self.root / ".deckhand" / "brief.json")["seo"]["indexnow_key"]
        self.assertTrue((self.root / "public" / f"{key}.txt").exists())
        code, again = self.dh("seo", "apply")
        self.assertEqual(again["written"], [])                                      # idempotent (and keeps the undo journal)
        code, out = self.dh("seo", "undo")
        self.assertEqual(code, 0, out)
        for p, b in before.items():
            self.assertEqual((self.root / p).read_bytes(), b, p)
        self.assertFalse((self.root / "app/robots.ts").exists())
        self.assertFalse((self.root / "lib/seo.ts").exists())

    def test_policy_by_path(self):
        for path, want in (("scratch", "seo apply"), ("existing", "seo apply"), ("pool", "DECISION NEEDED"), ("mine", "DECISION NEEDED")):
            steps = " ".join(guide._seo_steps(path))
            self.assertIn(want, steps, path)
        state.init(self.root, "Shop", path="pool")
        s = state.load(self.root)
        for p in ("define", "research", "plan", "build"):
            s["phases"][p] = {"status": "done"}
        for g in ("G1", "G2"):
            s["gates"][g] = {"status": "passed"}
        state.save(self.root, s)
        nxt = guide.next_step(self.root)
        self.assertEqual(nxt["phase"], "brand")
        self.assertTrue(any("DECISION NEEDED" in x for x in nxt["do"]))
        self.assertIn("pending", nxt)

    def test_preview_target_and_indexnow_ping(self):
        state.init(self.root, "Shop")
        out = deploy.target(self.root, "app-1", "http://1.2.3.4.sslip.io")
        self.assertIn("DH_NOINDEX=1", out["preview"])
        self.brief(domain="maisonpain.fr", seo__indexnow_key="a" * 32)
        sent = {}
        r = SEO.ping(self.root, ["https://maisonpain.fr/", "https://maisonpain.fr/about"], post=lambda body: sent.setdefault("b", json.loads(body)) and {"pinged": True})
        self.assertTrue(r["pinged"])
        self.assertEqual(sent["b"]["host"], "maisonpain.fr")
        self.assertEqual(sent["b"]["keyLocation"], "https://maisonpain.fr/" + "a" * 32 + ".txt")
        self.assertEqual(len(sent["b"]["urlList"]), 2)

    def test_brief_lists(self):
        state.init(self.root, "Shop")
        self.dh("brief", "set", "seo.keywords=wedding cakes lyon,sourdough lyon", "brand.social=https://instagram.com/x", "seo.local.hours=Mo-Fr 08:00-19:00,Sa 09:00-13:00")
        b = read_json(self.root / ".deckhand" / "brief.json")
        self.assertEqual(b["seo"]["keywords"], ["wedding cakes lyon", "sourdough lyon"])
        self.assertEqual(b["seo"]["local"]["hours"], ["Mo-Fr 08:00-19:00", "Sa 09:00-13:00"])
        self.assertEqual(b["brand"]["social"], ["https://instagram.com/x"])


if __name__ == "__main__":
    unittest.main()
