"""Deckhand bot for a Hermes no-agent cron job (generated by `dh ops add ... --runner hermes`).

Hermes runs this script on schedule with NO model call. Its stdout IS the delivered message, and empty stdout sends
nothing (the watchdog pattern). Secrets are read from the Deckhand vault by NAME at run time (Hermes cron scripts do not
inherit provider credentials) and are never printed. The bot's own progress output is swallowed: only an alert reaches
stdout.
"""
import contextlib
import io
import os
import runpy
import sys

SKILL = __SKILL__
PROJECT = __PROJECT__
BOT = __BOT__
NAMES = __NAMES__

sys.path.insert(0, SKILL)
from dhlib import profile  # noqa: E402

profile.use_project(PROJECT)
for n in NAMES:
    v = profile.secret(n) or os.environ.get(n)
    if v:
        os.environ[n] = v
os.environ["DECKHAND_NOTIFY"] = "stdout"
os.environ.setdefault("BOT_STATE_DIR", os.path.join(PROJECT, ".bot-state"))

sys.path.insert(0, os.path.dirname(BOT))
sys.argv = [BOT]
import notify  # noqa: E402  (the project's ops/bots/notify.py)


def _alert(text, title="deckhand"):
    sys.__stdout__.write(f"{title}\n{text}\n")
    return ["stdout"]


notify.deliver = _alert
try:
    with contextlib.redirect_stdout(io.StringIO()):
        runpy.run_path(BOT, run_name="__main__")
except SystemExit:
    pass
