// The SEO engine adds what is missing and improves what is weak — never the owner's own words — and undoes
// byte-exact. (A real `next build` of its output was proven by hand on Next 16.3.6; here: every file parses.)
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { seoInspect, seoApply, seoUndo } from '../lib/seo.mjs';

const require = createRequire(import.meta.url);
const { parse } = require('../lib/ast.cjs');

const LAYOUT = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: { canonical: "/" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className="min-h-full">{children}</body>
    </html>
  );
}
`;

function nextApp() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'dh-seo-'));
  const w = (f, t) => { fs.mkdirSync(path.dirname(path.join(dir, f)), { recursive: true }); fs.writeFileSync(path.join(dir, f), t); };
  w('package.json', JSON.stringify({ name: 'shop', dependencies: { next: '16.3.6', react: '19.0.0' } }));
  w('tsconfig.json', JSON.stringify({ compilerOptions: { paths: { '@/*': ['./*'] } } }));
  w('app/layout.tsx', LAYOUT);
  w('app/page.tsx', 'export default function Home() {\n  return <main><h1>Maison Pain</h1></main>;\n}\n');
  w('app/about/page.tsx', 'import type { Metadata } from "next";\n\nexport const metadata: Metadata = {\n  title: "Our bakers",\n};\n\nexport default function About() {\n  return <h1>About</h1>;\n}\n');
  w('app/menu/page.tsx', '"use client";\nexport default function Menu() { return <h1>Menu</h1>; }\n');
  w('app/(shop)/blog/[slug]/page.tsx', 'export default function Post() { return <h1>Post</h1>; }\n');
  return dir;
}

const PLAN = {
  site: { name: 'Maison Pain', url: 'https://maisonpain.fr', description: 'Sourdough baked every morning in Lyon.', tagline: 'Baked every morning', locale: 'en_US', languages: ['en'], themeColor: '#7c2d12' },
  jsonld: { '@context': 'https://schema.org', '@graph': [{ '@type': 'Bakery', name: 'Maison Pain </script><script>alert(1)</script>' }] },
  pages: [{ route: '/', title: 'Artisan bakery in Lyon — Maison Pain', description: 'Sourdough and cakes baked every morning in Lyon 2e.' }, { route: '/about', title: 'Ignored: the owner already wrote one', description: 'Meet the bakers.' }, { route: '/menu', title: 'Menu' }],
  robots: { ai: 'search-only', disallow: ['/account'], training: ['GPTBot', 'CCBot'] },
  llms: '# Maison Pain\n\n> Artisan bakery in Lyon.\n', indexnow: 'c'.repeat(32),
  genericTitles: ['Create Next App', 'Vite + React'], genericDescriptions: ['Generated by create next app'],
};
const read = (d, f) => fs.readFileSync(path.join(d, f), 'utf8');

test('inspect sees what the source has: routes (groups stripped), client pages, dynamic routes, the inherited canonical', () => {
  const dir = nextApp();
  const i = seoInspect(dir);
  assert.equal(i.router, 'app');
  assert.deepEqual(i.pages.map((p) => [p.route, p.client, p.dynamic]), [['/', false, false], ['/about', false, false], ['/blog/[slug]', false, true], ['/menu', true, false]]);
  assert.equal(i.layout.metadata.titleKind, 'string');
  assert.equal(i.layout.metadata.canonical, true);
  assert.equal(i.layout.lang, null);
  assert.equal(i.files.robots, null);
  assert.equal(i.jsonLd, false);
});

test('apply adds and improves, keeps the owner\'s words, fixes the inherited canonical, is idempotent and undoes byte-exact', () => {
  const dir = nextApp();
  const before = Object.fromEntries(['app/layout.tsx', 'app/page.tsx', 'app/about/page.tsx', 'app/menu/page.tsx'].map((f) => [f, read(dir, f)]));
  const r = seoApply(dir, PLAN);
  const layout = read(dir, 'app/layout.tsx');
  assert.match(layout, /title: \{ default: SITE\.name, template: `%s — \$\{SITE\.name\}` \}/);   // template title → the brand
  assert.match(layout, /description: SITE\.description/);
  assert.ok(!/canonical/.test(layout), 'a root-layout canonical makes every page claim to be the home page');
  assert.match(layout, /<html lang="en">/);
  assert.match(layout, /<JsonLd data=\{JSON_LD\} \/>/);
  assert.match(layout, /import \{ SITE, NOINDEX, JSON_LD \} from "@\/lib\/seo";/);
  assert.match(layout, /robots: NOINDEX \? \{ index: false, follow: false \} : \{ index: true, follow: true \}/);
  const about = read(dir, 'app/about/page.tsx');
  assert.match(about, /title: "Our bakers"/);                          // never overwritten
  assert.match(about, /alternates: \{ canonical: "\/about" \}/);
  assert.match(read(dir, 'app/page.tsx'), /title: \{ absolute: "Artisan bakery in Lyon — Maison Pain" \}/);   // brand already in it: no double brand
  assert.equal(read(dir, 'app/menu/page.tsx'), before['app/menu/page.tsx']);   // a client page cannot export metadata
  assert.ok(r.changes.some((c) => c.skipped && /use client/.test(c.skipped)));
  assert.ok(r.changes.some((c) => c.todo && /generateMetadata/.test(c.todo)));
  const robots = read(dir, 'app/robots.ts');
  assert.match(robots, /"\/account"/);
  assert.match(robots, /userAgent: \["GPTBot","CCBot"\], disallow: "\/"/);
  assert.match(read(dir, 'components/seo/json-ld.tsx'), /replace\(\/<\/g, "\\\\u003c"\)/);   // no string can close the script tag
  for (const f of r.written.filter((x) => /\.(tsx|ts)$/.test(x))) assert.doesNotThrow(() => parse(f, read(dir, f)), f);
  assert.ok(fs.existsSync(path.join(dir, 'public', 'c'.repeat(32) + '.txt')));
  assert.equal(seoApply(dir, PLAN).written.length, 0, 'idempotent');
  seoUndo(dir);
  for (const [f, t] of Object.entries(before)) assert.equal(read(dir, f), t, f);
  for (const f of ['app/robots.ts', 'lib/seo.ts', 'app/opengraph-image.tsx', 'public/llms.txt']) assert.ok(!fs.existsSync(path.join(dir, f)), f);
});

test('files the owner wrote are kept; ours are regenerated from the brief', () => {
  const dir = nextApp();
  fs.writeFileSync(path.join(dir, 'app/robots.ts'), 'export default function robots() { return { rules: [{ userAgent: "*", allow: "/" }] }; }\n');
  const r = seoApply(dir, PLAN);
  assert.match(read(dir, 'app/robots.ts'), /^export default function robots/);
  assert.ok(r.changes.some((c) => c.file === 'app/robots.ts' && c.kept));
  seoApply(dir, { ...PLAN, site: { ...PLAN.site, name: 'Maison Pain & Fils' } });
  assert.match(read(dir, 'lib/seo.ts'), /name: "Maison Pain & Fils"/);
});

test('static / Vite sites get head tags and static robots, sitemap and llms.txt', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'dh-seo-vite-'));
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'v', devDependencies: { vite: '6.0.0' } }));
  fs.writeFileSync(path.join(dir, 'index.html'), '<!doctype html>\n<html>\n  <head>\n    <title>Vite + React</title>\n  </head>\n  <body><div id="root"></div></body>\n</html>\n');
  const i = seoInspect(dir);
  assert.equal(i.router, 'static');
  assert.equal(i.index.spa, true);                                        // AI crawlers see an empty page: the audit says so
  seoApply(dir, PLAN);
  const h = read(dir, 'index.html');
  assert.match(h, /<html lang="en">/);
  assert.match(h, /<title>Artisan bakery in Lyon — Maison Pain<\/title>/);
  assert.match(h, /<link rel="canonical" href="https:\/\/maisonpain.fr\/" \/>/);
  assert.match(h, /application\/ld\+json/);
  assert.ok(!h.includes('</script><script>alert(1)'), 'JSON-LD is escaped');
  assert.match(read(dir, 'public/robots.txt'), /Sitemap: https:\/\/maisonpain.fr\/sitemap.xml/);
  assert.match(read(dir, 'public/sitemap.xml'), /<loc>https:\/\/maisonpain.fr\/about<\/loc>/);
});

test('undo refuses to throw away an edit made after the apply, unless forced (final audit Y6)', () => {
  const dir = nextApp();
  const r = seoApply(dir, PLAN);
  const f = r.written[0];
  fs.appendFileSync(path.join(dir, f), '\n// owner edit\n');
  assert.throws(() => seoUndo(dir), (e) => e.code === 'FILE_CHANGED' && e.files.includes(f));
  assert.match(read(dir, f), /owner edit/);
  seoUndo(dir, { force: true });
});
