#!/usr/bin/env node
// Try-on playground: a real Next.js site (Deckhand's own scaffold + the default compose) kept in this repo as SOURCE ONLY,
// so any try-on test can start from it instead of building a site from scratch (create-next-app + npm install + compose).
//
//   node playground/playground.mjs restore [--to DIR]      copy the site to DIR (default ~/deckhand-playground/tryon-site),
//                                                           add the kitchen sink, install dependencies, make it a git repo
//   node playground/playground.mjs reset   [--to DIR]      throw away every try-on change: source back to the snapshot
//   node playground/playground.mjs start   [--to DIR]      try-on setup + dev server + try-on proxy; prints the URLs, Ctrl+C stops
//   node playground/playground.mjs kitchen --to DIR         (re)write only the kitchen-sink page and its components
//   node playground/playground.mjs snapshot --from DIR      refresh tryon-site/ from a site you built (paths and try-on state stripped)
//
// The kitchen sink (/kitchen-sink) shows one owner element for EVERY slot kind try-on knows (hero, pricing, tabs, dialog,
// table, sidebar…), written from the fit-check's own reference sections (tryon/lib/fitcheck.mjs), so it never drifts.
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SITE = path.join(HERE, 'tryon-site');
const SKILL = path.resolve(process.env.DECKHAND_SKILL || path.join(HERE, '..', 'skills', 'deckhand'));
const DEFAULT_DIR = path.join(os.homedir(), 'deckhand-playground', 'tryon-site');
const IS_WIN = process.platform === 'win32';

// what a snapshot keeps: source only (never node_modules, .next, .env, git history, run state, logs, try-on state)
const KEEP = ['app', 'components', 'lib', 'public', 'package.json', 'package-lock.json', 'tsconfig.json', 'postcss.config.mjs', 'next.config.ts', '.gitignore'];
const KEEP_DECKHAND = ['brief.json', 'sitemap.json', 'demo-copy.json'];
const SKIP_DIRS = new Set(['node_modules', '.next', '.git', 'dh-tryon']);
const TEXT = /\.(tsx?|jsx?|mjs|cjs|json|css|md|svg|txt|html|ya?ml)$/i;

const log = (...a) => process.stderr.write(a.join(' ') + '\n');

function copyTree(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (e.isDirectory()) copyTree(s, d);
    else if (TEXT.test(e.name)) fs.writeFileSync(d, fs.readFileSync(s, 'utf8').replace(/\r\n/g, '\n'));   // LF in the repo, always
    else fs.copyFileSync(s, d);
  }
}

/** Refresh tryon-site/ from a site someone built. Nothing that is local to their machine or to a try-on session comes along. */
export function snapshot(from) {
  const src = path.resolve(from);
  if (!fs.existsSync(path.join(src, 'package.json'))) throw new Error(`${src} is not a site (no package.json)`);
  fs.rmSync(SITE, { recursive: true, force: true });
  fs.mkdirSync(SITE, { recursive: true });
  for (const k of KEEP) {
    const s = path.join(src, k);
    if (!fs.existsSync(s)) continue;
    if (fs.statSync(s).isDirectory()) copyTree(s, path.join(SITE, k));
    else fs.writeFileSync(path.join(SITE, k), TEXT.test(k) || k === '.gitignore' ? fs.readFileSync(s, 'utf8').replace(/\r\n/g, '\n') : fs.readFileSync(s));
  }
  // try-on setup patches next.config.ts to proxy the overlay: the snapshot is the state BEFORE try-on touched it
  if (fs.existsSync(path.join(src, '.git'))) {
    const r = spawnSync('git', ['show', 'HEAD:next.config.ts'], { cwd: src, encoding: 'utf8' });
    if (r.status === 0) fs.writeFileSync(path.join(SITE, 'next.config.ts'), r.stdout.replace(/\r\n/g, '\n'));
  }
  fs.mkdirSync(path.join(SITE, '.deckhand'), { recursive: true });
  for (const f of KEEP_DECKHAND) {
    const s = path.join(src, '.deckhand', f);
    if (fs.existsSync(s)) fs.writeFileSync(path.join(SITE, '.deckhand', f), fs.readFileSync(s, 'utf8').replace(/\r\n/g, '\n'));
  }
  // the components the try-on staged are not part of the site
  fs.rmSync(path.join(SITE, 'components', 'dh-tryon'), { recursive: true, force: true });
  fs.rmSync(path.join(SITE, 'components', 'ref'), { recursive: true, force: true });       // regenerated by `kitchen`
  fs.rmSync(path.join(SITE, 'app', 'kitchen-sink'), { recursive: true, force: true });
  const skillVersion = /^version:\s*"?([\d.]+)/m.exec(fs.readFileSync(path.join(SKILL, 'SKILL.md'), 'utf8'))?.[1] || null;
  const sections = fs.existsSync(path.join(SITE, 'components', 'sections')) ? fs.readdirSync(path.join(SITE, 'components', 'sections')).sort() : [];
  const manifest = { what: 'Deckhand try-on playground: scaffold + default compose (source only)', deckhand: skillVersion, sections };
  fs.writeFileSync(path.join(HERE, 'playground.json'), JSON.stringify(manifest, null, 2) + '\n');
  return manifest;
}

/** One owner element per slot kind, from the fit-check's own reference sections, on /kitchen-sink. */
export async function kitchen(dir) {
  const to = path.resolve(dir);
  const { REFERENCE } = await import(pathToFileURL(path.join(SKILL, 'tryon', 'lib', 'fitcheck.mjs')).href);
  const refDir = path.join(to, 'components', 'ref');
  fs.rmSync(refDir, { recursive: true, force: true });
  fs.mkdirSync(refDir, { recursive: true });
  const rows = [];
  for (const [slot, ref] of Object.entries(REFERENCE)) {
    fs.writeFileSync(path.join(refDir, `${slot}.tsx`), ref.code);
    const name = /export function ([A-Z]\w*)/.exec(ref.code)?.[1];
    if (name) rows.push({ slot, name, file: `components/ref/${slot}` });
  }
  const imports = rows.map((r, i) => `import { ${r.name} as R${i} } from "@/${r.file}";`).join('\n');
  const blocks = rows.map((r, i) => `      <section id="slot-${r.slot}" className="space-y-3">
        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">${r.slot}</p>
        <div className="relative min-h-16 overflow-hidden rounded-lg border border-dashed p-4" style={{ transform: "translateZ(0)" }}>
          <R${i} />
        </div>
      </section>`).join('\n');
  const page = `// Written by playground.mjs: one owner element for every slot kind try-on knows. Click any of them in the try-on proxy.
${imports}

export default function KitchenSink() {
  return (
    <main className="mx-auto max-w-5xl space-y-12 p-8">
      <h1 className="text-3xl font-bold">Try-on kitchen sink</h1>
      <p className="text-sm text-muted-foreground">${rows.length} kinds of section, each as an owner would write it.</p>
${blocks}
    </main>
  );
}
`;
  fs.mkdirSync(path.join(to, 'app', 'kitchen-sink'), { recursive: true });
  fs.writeFileSync(path.join(to, 'app', 'kitchen-sink', 'page.tsx'), page);
  return { slots: rows.map((r) => r.slot), page: 'app/kitchen-sink/page.tsx' };
}

function run(cmd, args, cwd, opts = {}) {
  const r = spawnSync(cmd, args, { cwd, encoding: 'utf8', shell: IS_WIN && /^(npm|npx)$/.test(cmd), stdio: opts.inherit ? 'inherit' : 'pipe' });
  if (r.status !== 0 && !opts.soft) throw new Error(`${cmd} ${args.join(' ')} failed: ${(r.stderr || r.stdout || '').slice(-400)}`);
  return r;
}

/** Copy the snapshot to `dir`, add the kitchen sink, install, make it a git repo. Safe to run over an existing playground. */
export async function restore(dir = DEFAULT_DIR, { install = true } = {}) {
  const to = path.resolve(dir);
  if (!fs.existsSync(path.join(SITE, 'package.json'))) throw new Error('playground/tryon-site is empty: run `snapshot --from <a site>` first');
  fs.rmSync(path.join(to, 'app'), { recursive: true, force: true });
  fs.rmSync(path.join(to, 'components'), { recursive: true, force: true });
  fs.rmSync(path.join(to, '.deckhand', 'tryon'), { recursive: true, force: true });
  fs.mkdirSync(to, { recursive: true });
  copyTree(SITE, to);
  const k = await kitchen(to);
  if (install && !fs.existsSync(path.join(to, 'node_modules'))) {
    log('installing dependencies (once)…');
    run('npm', ['install', '--no-audit', '--no-fund'], to);
  }
  if (!fs.existsSync(path.join(to, '.git'))) {
    run('git', ['init', '-q'], to);
  }
  run('git', ['add', '-A'], to);
  run('git', ['-c', 'user.name=playground', '-c', 'user.email=playground@localhost', 'commit', '-qm', 'playground: snapshot + kitchen sink', '--allow-empty'], to, { soft: true });
  return { dir: to, kitchen: k.slots.length, sections: JSON.parse(fs.readFileSync(path.join(HERE, 'playground.json'), 'utf8')).sections };
}

const freePort = () => new Promise((res, rej) => { const s = net.createServer(); s.once('error', rej); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => res(p)); }); });
const answers = (url) => new Promise((res) => { http.get(url, (r) => { r.resume(); res(r.statusCode); }).on('error', () => res(0)).setTimeout(4000, function () { this.destroy(); }); });
const killTree = (child) => { if (!child || child.killed) return; if (IS_WIN) spawnSync('taskkill', ['/pid', String(child.pid), '/T', '/F']); else child.kill('SIGTERM'); };

/** try-on setup, the dev server and the try-on proxy on free ports. `stop()` ends both. */
export async function startPlayground(dir = DEFAULT_DIR) {
  const to = path.resolve(dir);
  const cli = path.join(SKILL, 'tryon', 'cli.mjs');
  run('node', [cli, 'setup', '--project', to], to);
  const devPort = await freePort();
  const dev = spawn('npm', ['run', 'dev', '--', '--port', String(devPort)], { cwd: to, shell: IS_WIN, stdio: 'ignore', windowsHide: true });
  const devUrl = `http://127.0.0.1:${devPort}`;
  for (let i = 0, st = 0; i < 240 && (st = await answers(devUrl + '/')) < 200; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (i === 239) { killTree(dev); throw new Error('the dev server did not answer within 2 minutes'); }
  }
  const proxyPort = await freePort();
  const serve = spawn('node', [cli, 'serve', '--project', to, '--port', String(proxyPort), '--target', devUrl], { cwd: to, stdio: 'ignore', windowsHide: true });
  const open = `http://127.0.0.1:${proxyPort}`;
  for (let i = 0; i < 60 && (await answers(open + '/')) < 200; i++) await new Promise((r) => setTimeout(r, 500));
  return { dir: to, dev: devUrl, open, stop() { killTree(serve); killTree(dev); } };
}

const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };

async function main() {
  const cmd = process.argv[2];
  const to = arg('to', DEFAULT_DIR);
  try {
    if (cmd === 'snapshot') console.log(JSON.stringify({ ok: true, ...snapshot(arg('from')) }));
    else if (cmd === 'kitchen') console.log(JSON.stringify({ ok: true, ...(await kitchen(arg('to'))) }));
    else if (cmd === 'restore' || cmd === 'reset') console.log(JSON.stringify({ ok: true, ...(await restore(to)) }));
    else if (cmd === 'start') {
      const p = await startPlayground(to);
      console.log(JSON.stringify({ ok: true, open: p.open, dev: p.dev, note: 'open the URL (also /kitchen-sink), click Try-on. Ctrl+C stops.' }));
      const bye = () => { p.stop(); process.exit(0); };
      process.on('SIGINT', bye); process.on('SIGTERM', bye);
      setInterval(() => {}, 1 << 30);
    } else { console.log(JSON.stringify({ ok: false, usage: 'playground.mjs restore|reset|start|kitchen|snapshot [--to DIR] [--from DIR]' })); process.exit(2); }
  } catch (e) { console.log(JSON.stringify({ ok: false, error: String(e.message || e) })); process.exit(1); }
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) main();
